[package]
name = "control_apps"
version = "0.1.0"
authors = ["Philip Linden <lindenphilipj@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pid_control = "0.7.2"
linearkalman = "0.1.3"
rulinalg = "0.4.2"
