# controller settings
target_altitude_m = 24_000.0
vent_kp = 1.0E-5
vent_ki = 1.0E-8
vent_kd = 1.0E-1
dump_kp = 1.0E-4
dump_ki = 1.0E-6
dump_kd = 1.0E-1
altitude_floor_m = 15_000.0
error_deadzone_m = 100.0
error_ready_threshold_m = 1000.0
speed_deadzone_m_s = 0.2
tlm_max_age_s = 2.0
min_ballast_kg = 0.01
ctrl_rate_hz = 10.0
