name: Rust

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build-support-apps:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: support_apps
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  build-control-apps:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: control_apps
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
